status_dict = {
    "Wheel rim": "Aro da roda",
    "Damage": "Dano",
    "Drivetrain": "Transmissão",
    "Fuel rig": "Equipamento de combustível",
    "Oil line": "Linha de óleo",
    "Safety": "Segurança",
    "Safety concerns": "Preocupações de segurança",
    "Stalled": "Parado",
    "Track rod": "Barra de direção",
    "+20 Laps": "+20 Voltas",
    "+21 Laps": "+21 Voltas",
    "+23 Laps": "+23 Voltas",
    "+26 Laps": "+26 Voltas",
    "+29 Laps": "+29 Voltas",
    "+30 Laps": "+30 Voltas",
    "+42 Laps": "+42 Voltas",
    "+44 Laps": "+44 Voltas",
    "+46 Laps": "+46 Voltas",
    "Brake duct": "Conduto de freio",
    "Cooling system": "Sistema de refrigeração",
    "Crankshaft": "Virabrequim",
    "CV joint": "Junta homocinética",
    "Debris": "Detritos",
    "Driver Seat": "Assento do motorista",
    "Engine fire": "Incêndio no motor",
    "Engine misfire": "Falha de motor",
    "Eye injury": "Lesão ocular",
    "Launch control": "Controle de lançamento",
    "Not restarted": "Não reiniciado",
    "Refuelling": "Reabastecimento",
    "Safety belt": "Cinto de segurança",
    "Seat": "Assento",
    "Tyre puncture": "Pneu furado",
    "Underweight": "Abaixo do peso",
    "Finished": "Finalizado",
    "+1 Lap": "+1 Volta",
    "Engine": "Motor",
    "+2 Laps": "+2 Voltas",
    "Accident": "Acidente",
    "Collision": "Colisão",
    "Gearbox": "Caixa de câmbio",
    "Spun off": "Saída da pista",
    "+3 Laps": "+3 Voltas",
    "Suspension": "Suspensão",
    "+4 Laps": "+4 Voltas",
    "Transmission": "Transmissão",
    "Electrical": "Elétrico",
    "Brakes": "Freios",
    "Withdrew": "Retirado",
    "+5 Laps": "+5 Voltas",
    "Clutch": "Embreagem",
    "Not classified": "Não classificado",
    "Fuel system": "Sistema de combustível",
    "+6 Laps": "+6 Voltas",
    "Disqualified": "Desclassificado",
    "Turbo": "Turbo",
    "Hydraulics": "Hidráulico",
    "Overheating": "Superaquecimento",
    "Ignition": "Ignição",
    "Oil leak": "Vazamento de óleo",
    "Retired": "Abandonado",
    "Throttle": "Acelerador",
    "+7 Laps": "+7 Voltas",
    "Out of fuel": "Sem combustível",
    "Halfshaft": "Semi-eixo",
    "Wheel": "Roda",
    "Oil pressure": "Pressão de óleo",
    "Fuel pump": "Bomba de combustível",
    "Differential": "Diferencial",
    "Collision damage": "Dano de colisão",
    "Tyre": "Pneu",
    "Handling": "Manejo",
    "+8 Laps": "+8 Voltas",
    "Fuel leak": "Vazamento de combustível",
    "Steering": "Direção",
    "Radiator": "Radiador",
    "Power Unit": "Unidade de Potência",
    "Puncture": "Pneu furado",
    "+9 Laps": "+9 Voltas",
    "Wheel bearing": "Rolamento de roda",
    "Injection": "Injeção",
    "Fuel pressure": "Pressão de combustível",
    "+10 Laps": "+10 Voltas",
    "Water leak": "Vazamento de água",
    "Alternator": "Alternador",
    "Physical": "Físico",
    "Exhaust": "Escape",
    "Chassis": "Chassi",
    "Mechanical": "Mecânico",
    "Magneto": "Magneto",
    "Driveshaft": "Eixo de transmissão",
    "Axle": "Eixo",
    "Heat shield fire": "Incêndio no escudo de calor",
    "+11 Laps": "+11 Voltas",
    "Battery": "Bateria",
    "Power loss": "Perda de potência",
    "Distributor": "Distribuidor",
    "Oil pump": "Bomba de óleo",
    "+13 Laps": "+13 Voltas",
    "Injury": "Lesão",
    "+12 Laps": "+12 Voltas",
    "+14 Laps": "+14 Voltas",
    "Oil pipe": "Tubulação de óleo",
    "Broken wing": "Asa quebrada",
    "Electronics": "Eletrônicos",
    "Driver unwell": "Motorista indisposto",
    "Rear wing": "Asa traseira",
    "Vibrations": "Vibrações",
    "+15 Laps": "+15 Voltas",
    "Water pressure": "Pressão de água",
    "Wheel nut": "Porca da roda",
    "Excluded": "Excluído",
    "+16 Laps": "+16 Voltas",
    "+17 Laps": "+17 Voltas",
    "Injured": "Ferido",
    "Water pump": "Bomba d'água",
    "ERS": "ERS",
    "Front wing": "Asa dianteira",
    "Supercharger": "Supercharger",
    "Technical": "Técnico",
    "+18 Laps": "+18 Voltas",
    "+19 Laps": "+19 Voltas",
    "+22 Laps": "+22 Voltas",
    "+24 Laps": "+24 Voltas",
    "Fuel": "Combustível",
    "Pneumatics": "Pneumáticos",
    "Undertray": "Base inferior",
    "+25 Laps": "+25 Voltas",
    "Fatal accident": "Acidente fatal",
    "Fire": "Fogo",
    "Fuel pipe": "Tubulação de combustível",
    "Illness": "Doença",
    "Spark plugs": "Velas de ignição",
    "Water pipe": "Tubo de água"
}
